### ISSUE TITLE
Removal of this package from dub-registry broke dub's testsuite

### ISSUE THREAD

**Issue by MartinNowak** [p0nce/gitcompatibledubpackage#1]
The dub testsuite currently uses this package in 2 tests.
Could you please reregister it and/or transfer ownership to someone else?

**Comment by MartinNowak** [comment]
Just registered it under my fork, let me know if that works for you.
http://code.dlang.org/my_packages/gitcompatibledubpackage

**Comment by p0nce** [comment]
Hi Martin,

I'm reall sorry for the hiccup.
I was cleaning up my repos in a too optimistic way, and believed it wasn't used by the DUB testing. 100% OK with registering the fork instead, feels cleaner to me if it's you or Sonke that control this repo.
